/* eslint-disable tailwindcss/no-custom-classname */
"use client";
// import { Metadata } from "next";
import React from "react";
import { signInFormSchema } from "../../../../lib/form-schema";
import { zodResolver } from "@hookform/resolvers/zod";

import { z } from "zod";
import { useForm } from "react-hook-form";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "../../../../components/ui/form";

import { Input } from "../../../../components/ui/input";
// import { Metadata } from "next";
import { Button } from "../../../../components/ui/button";
import Link from "next/link";

// export const metadata: Metadata = {
//   title: "Sign In",
//   description: "Generated by create next app",
// };

const SignInPage = () => {
  const form = useForm<z.infer<typeof signInFormSchema>>({
    resolver: zodResolver(signInFormSchema),
  });
  const onSubmit = (val: z.infer<typeof signInFormSchema>) => {
    console.log(val);
  };
  return (
    <div className="relative h-screen w-full">
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
        <div className="border-border border p-5">
          <div className="mb-2 text-center text-2xl font-semibold">
            Login Account
          </div>
          <div className="text-sm text-gray-500">
            Enter your email to access dashboard
          </div>

          <Form {...form}>
            <form
              onSubmit={form.handleSubmit(onSubmit)}
              className="mt-5 space-y-5"
            >
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <Input
                        className="w-[450px]"
                        placeholder="Enter your email..."
                        {...field}
                      />
                    </FormControl>

                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Password</FormLabel>
                    <FormControl>
                      <Input
                        className="w-[450px]"
                        placeholder="Enter your Password"
                        {...field}
                      />
                    </FormControl>

                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button className="w-full">Sign In</Button>
              <div className="text-sm">Don&apos;t have an account</div>
              <Link href="/auth/signup" className="text-primary">
                SignUp
              </Link>
            </form>
          </Form>
        </div>
      </div>
    </div>
  );
};

export default SignInPage;
